
version: '3.9'

services:
  pytorch:
    image: 10.156.168.113:7887/pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
    container_name: pytorch-dev
    restart: unless-stopped
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    ports:
      - "33334:8080"
    volumes:
      - ./:/workspace   # 挂载当前目录
    working_dir: /workspace
    command: bash -c "sleep infinity"  # 保持容器常驻
    stdin_open: true
    tty: true
