apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379        # Service 内部端口
      targetPort: 6379  # Pod 内部 Redis 端口
      nodePort: 32000   # 节点暴露的端口（外部访问用），范围必须在 30000–32767
