apiVersion: v1
kind: Pod
metadata:
  name: pytorch-pod
  labels:
    app: pytorch
spec:
  containers:
  - name: pytorch
    image: 10.156.168.113:7887/pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
    command: ["/bin/bash", "-c", "sleep infinity"]
    tty: true
    stdin: true
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
